# Generated by Django 3.2.8 on 2022-07-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
